Use mmap64 on Linux.
rust-lang/backtrace-rs pull request #501
Opened 2022-12-06 22:43 UTC by mikebenfield

mmap is a non-LFS function and due to its usage here will appear in binaries produced by rustc.

This is relevant to rust-lang/rust#94173.

2022-12-06 23:04 UTC, mikebenfield commented
```
cargo test --features gimli-symbolize --manifest-path crates/without_debuginfo/Cargo.toml
```

fails in CI on Ubuntu but passes on my machine. It's not clear to me how my change could cause this.

2022-12-14 22:15 UTC, mikebenfield commented
Alright, this test fails on someone else's commit too, so I guess my PR is not responsible. 

https://github.com/rust-lang/backtrace-rs/actions/runs/3697730052/jobs/6263075709

2022-12-24 22:19 UTC, mochaaP requested changes

2022-12-24 22:19 UTC, mochaaP commented on src/symbolize/gimli/mmap_unix.rs
> +#[cfg(target_os = "linux")]
should only use mmap64 on glibc, see <https://github.com/rust-lang/rust/issues/94173#issuecomment-1358619183>

2023-02-24 23:30 UTC, workingjubilee commented
See also:
- https://github.com/rust-lang/libc/issues/2934
- https://github.com/rust-lang/libc/pull/2935

2023-04-21 21:16 UTC, inglorion commented
I would like to get this merged. mikebenfield told me I'm free to take over the work. Can we continue on this PR or should I create a new one?

2023-06-21 18:34 UTC, workingjubilee commented
Okay. Most of the CI checks pass now, and the remainder don't because of... missing the nightly toolchain? Whatever. This looks good, merging.

2023-06-21 18:35 UTC, workingjubilee approved these changes

2023-06-21 18:35 UTC, merged