Document mmap safety
rust-lang/backtrace-rs pull request #674
Opened 2024-09-22 03:47 UTC by CraftSpider

Supercedes #667

Document safety preconditions and reasoning for why they're followed. I'd like to push the unsafety down another level, or just remove the `mmap` function (make `Mmap` a common type with sys impls for the platform-specific bits), but those both are a lot more work.

2024-09-22 04:08 UTC, philipc commented on src/symbolize/gimli.rs
> +    //         executable code of the process. Modifying them would cause crashes or UB anyways.
This is true for some but not all uses of mmap in this crate. DWARF can be in a separate file that is not loaded by the dynamic linker or kernel (.dSYM on macOS, .debug/.dwz/.dwp on linux, or unpacked object files on both).

That doesn't mean we should use `fs::read` for those though. We don't need to read all of the DWARF, and doing so would affect performance and memory usage.

2026-07-05 06:29 UTC, hkBst requested changes

2026-07-05 06:29 UTC, hkBst commented on src/symbolize/gimli/elf.rs
> +            // SAFETY: See `super::mmap` function
The point of a safety comment for a use is to explain why that use is safe. I'm not sure what this is referring to and why it cannot explain safety directly instead.

2026-07-13 16:51 UTC, CraftSpider commented
This PR is vastly out-of-date, and I don't have the time right now to update it. So I'm just going to close it for now.

2026-07-13 16:51 UTC, closed without merging