Attempt to fix ARM32 Windows
rust-lang/backtrace-rs pull request #685
Opened 2024-12-20 13:55 UTC by bdbai

Currently `thumbv7a-pc-windows-msvc` and `thumbv7a-pc-windows-msvc` fails to build due to lack of a few symbols generated by `windows-targets`. As `backtrace` being a dependency of Rust `std`, `build-std` feature targeting these platforms also fails. The fix here is definitely not a good idea which is modifying a generated file, but it shows the possibility to have the issue solved at least to unblock `build-std` on these platforms.

This was how I verified it using `1.85.0-nightly` toolchain:

```bash
cargo +nightly build -Z build-std=core,alloc,panic_abort --target thumbv7a-uwp-windows-msvc --no-default-features
cargo +nightly build -Z build-std=core,alloc,panic_abort --target thumbv7a-pc-windows-msvc --no-default-features
```
<details>
<summary>which produced the following output:</summary>

```
cargo +nightly build -Z build-std=core,alloc,panic_abort --target thumbv7a-uwp-windows-msvc --no-default-features                                         ─╯
   Compiling backtrace v0.3.74 (<path-to>\backtrace-rs)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s

cargo +nightly build -Z build-std=core,alloc,panic_abort --target thumbv7a-pc-windows-msvc --no-default-features                                          ─╯
   Compiling backtrace v0.3.74 (<path-to>\backtrace-rs)
warning: unnecessary `unsafe` block
   --> src\backtrace\dbghelp32.rs:218:5
    |
218 |     unsafe {
    |     ^^^^^^ unnecessary `unsafe` block
    |
    = note: `#[warn(unused_unsafe)]` on by default

warning: creating a mutable reference to mutable static is discouraged
   --> src\dbghelp.rs:115:21
    |
115 |                       DBGHELP.$name().unwrap()
    |                       ^^^^^^^ mutable reference to mutable static
...
128 | / dbghelp! {
129 | |     extern "system" {
130 | |         fn SymGetOptions() -> u32;
131 | |         fn SymSetOptions(options: u32) -> u32;
...   |
223 | | }
    | |_- in this macro invocation
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives
    = note: `#[warn(static_mut_refs)]` on by default
    = note: this warning originates in the macro `dbghelp` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: creating a mutable reference to mutable static is discouraged
   --> src\dbghelp.rs:115:21
    |
115 |                       DBGHELP.$name().unwrap()
    |                       ^^^^^^^ mutable reference to mutable static
...
128 | / dbghelp! {
129 | |     extern "system" {
130 | |         fn SymGetOptions() -> u32;
131 | |         fn SymSetOptions(options: u32) -> u32;
...   |
223 | | }
    | |_- in this macro invocation
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives
    = note: this warning originates in the macro `dbghelp` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: creating a mutable reference to mutable static is discouraged
   --> src\dbghelp.rs:321:9
    |
321 |         DBGHELP.ensure_open()?;
    |         ^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: creating a mutable reference to mutable static is discouraged
   --> src\dbghelp.rs:333:20
    |
333 |         let orig = DBGHELP.SymGetOptions()?();
    |                    ^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: creating a mutable reference to mutable static is discouraged
   --> src\dbghelp.rs:338:9
    |
338 |         DBGHELP.SymSetOptions()?(orig | SYMOPT_DEFERRED_LOADS);
    |         ^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: creating a mutable reference to mutable static is discouraged
   --> src\dbghelp.rs:352:9
    |
352 |         DBGHELP.SymInitializeW()?(GetCurrentProcess(), ptr::null_mut(), TRUE);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: creating a mutable reference to mutable static is discouraged
   --> src\dbghelp.rs:366:12
    |
366 |         if DBGHELP.SymGetSearchPathW()?(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: creating a mutable reference to mutable static is discouraged
   --> src\dbghelp.rs:386:9
    |
386 |         DBGHELP.EnumerateLoadedModulesW64()?(
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: creating a mutable reference to mutable static is discouraged
   --> src\dbghelp.rs:395:9
    |
395 |         DBGHELP.SymSetSearchPathW()?(GetCurrentProcess(), new_search_path.as_ptr());
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
    = note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives

warning: `backtrace` (lib) generated 24 warnings (14 duplicates)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.23s
```

</details>

Any input on better ways to handle this will be appreciated! In Rust std I can see it's solved here https://github.com/rust-lang/rust/blob/8a1f8039a7ded79d3d4fe97b110016d89f2b11e2/src/tools/generate-windows-sys/src/main.rs#L8 . Not sure if we can apply something similar here.

Xref: #572 #634

2024-12-25 05:55 UTC, workingjubilee commented
@bdbai I am curious what use the 32-bit Windows Arm target is being put to? It is a target unmaintained by the OS vendor... as in, the entire OS is unmaintained for that target... and no one has signed up to maintain the target on the Rust end.

As for the CONTEXT structure, the std definition provided that you linked to is an uninhabited type (no variants), so it cannot actually be interacted with in the conventional sense... hmm...

2024-12-25 06:52 UTC, bdbai commented
@workingjubilee 

> I am curious what use the 32-bit Windows Arm target is being put to?

Some examples running Windows ARM32: Surface RT, Windows Phone and Windows 10 IoT Core

> As for the CONTEXT structure, the std definition provided that you linked to is an uninhabited type (no variants), so it cannot actually be interacted with in the conventional sense... hmm...

In std the CONTEXT structure for ARM is only used in pointer form (like https://github.com/rust-lang/rust/blob/41f2f5c0b7d5fb68685030edc62e66a21cae38ef/library/std/src/sys/pal/windows/c/windows_sys.rs#L65) so we didn't bother to fill up all fields inside but instead treat it as an opaque FFI type. However in backtrace `https://github.com/rust-lang/backtrace-rs/blob/26ab4afa46e889f2f4c81e5f5022f61569f02d16/src/backtrace/dbghelp32.rs#L214` we are actually [reading the values](https://github.com/rust-lang/backtrace-rs/blob/26ab4afa46e889f2f4c81e5f5022f61569f02d16/src/backtrace/dbghelp32.rs#L214) inside so the complete definition is required.

2024-12-25 06:58 UTC, workingjubilee commented
@bdbai Yes, we don't really have support for any of those targets except for their 64-bit versions. But I wasn't really asking you to quote OS names at me, I'm curious what *you* actually use it for.

2024-12-25 07:05 UTC, bdbai commented
@workingjubilee Personally I am writing UWP apps (https://github.com/YtFlow/YtFlowApp) specifically targeting both desktop and mobile as some users including me are still using Windows Phone. The [core](https://github.com/YtFlow/YtFlowCore) part is written in Rust hence needs to cross compile to `thumbv7a-uwp-windows-msvc`.

2024-12-25 07:06 UTC, workingjubilee commented
I see! @ChrisDenton You lost the bet, I suppose?

@bdbai Do you have a citation for the 32-bit Arm Windows target CONTEXT definition? It is, for perhaps obvious reasons, hard to find on Microsoft's documentation.

2024-12-25 07:10 UTC, bdbai commented
fyi the definitions are migrated from `winapi` crate here https://github.com/retep998/winapi-rs/blob/5b1829956ef645f3c2f8236ba18bb198ca4c2468/src/um/winnt.rs#L1468

2024-12-25 07:19 UTC, bdbai commented
Copying these from Windows SDK (10.0.22621.0):
```c
//
// Specify the number of breakpoints and watchpoints that the OS
// will track. Architecturally, ARM supports up to 16. In practice,
// however, almost no one implements more than 4 of each.
//

#define ARM_MAX_BREAKPOINTS     8
#define ARM_MAX_WATCHPOINTS     1

//
// Context Frame
//
//  This frame has a several purposes: 1) it is used as an argument to
//  NtContinue, 2) it is used to constuct a call frame for APC delivery,
//  and 3) it is used in the user level thread creation routines.
//
//
// The flags field within this record controls the contents of a CONTEXT
// record.
//
// If the context record is used as an input parameter, then for each
// portion of the context record controlled by a flag whose value is
// set, it is assumed that that portion of the context record contains
// valid context. If the context record is being used to modify a threads
// context, then only that portion of the threads context is modified.
//
// If the context record is used as an output parameter to capture the
// context of a thread, then only those portions of the thread's context
// corresponding to set flags will be returned.
//
// CONTEXT_CONTROL specifies Sp, Lr, Pc, and Cpsr
//
// CONTEXT_INTEGER specifies R0-R12
//
// CONTEXT_FLOATING_POINT specifies Q0-Q15 / D0-D31 / S0-S31
//
// CONTEXT_DEBUG_REGISTERS specifies up to 16 of DBGBVR, DBGBCR, DBGWVR,
//      DBGWCR.
//

typedef struct _NEON128 {
    ULONGLONG Low;
    LONGLONG High;
} NEON128, *PNEON128;

typedef struct DECLSPEC_ALIGN(8) DECLSPEC_NOINITALL _CONTEXT {

    //
    // Control flags.
    //

    DWORD ContextFlags;

    //
    // Integer registers
    //

    DWORD R0;
    DWORD R1;
    DWORD R2;
    DWORD R3;
    DWORD R4;
    DWORD R5;
    DWORD R6;
    DWORD R7;
    DWORD R8;
    DWORD R9;
    DWORD R10;
    DWORD R11;
    DWORD R12;

    //
    // Control Registers
    //

    DWORD Sp;
    DWORD Lr;
    DWORD Pc;
    DWORD Cpsr;

    //
    // Floating Point/NEON Registers
    //

    DWORD Fpscr;
    DWORD Padding;
    union {
        NEON128 Q[16];
        ULONGLONG D[32];
        DWORD S[32];
    } DUMMYUNIONNAME;

    //
    // Debug registers
    //

    DWORD Bvr[ARM_MAX_BREAKPOINTS];
    DWORD Bcr[ARM_MAX_BREAKPOINTS];
    DWORD Wvr[ARM_MAX_WATCHPOINTS];
    DWORD Wcr[ARM_MAX_WATCHPOINTS];

    DWORD Padding2[2];

} CONTEXT, *PCONTEXT;
```

2024-12-25 08:04 UTC, workingjubilee requested changes

2024-12-25 08:24 UTC, bdbai commented on src/windows_sys.rs
> +        pub struct CONTEXT_u([u64; 32]);
Fixed in https://github.com/rust-lang/backtrace-rs/pull/685/commits/d468f713270386f9fa5a5bb4404229219141c80e

2024-12-25 08:24 UTC, bdbai commented on src/windows_sys.rs
> +            pub Sp: u32,
Fixed in https://github.com/rust-lang/backtrace-rs/pull/685/commits/d468f713270386f9fa5a5bb4404229219141c80e

2024-12-25 08:24 UTC, bdbai commented on src/windows_sys.rs
> +            pub Fpsrc: u32,
Fixed in https://github.com/rust-lang/backtrace-rs/pull/685/commits/d468f713270386f9fa5a5bb4404229219141c80e

2024-12-25 08:24 UTC, bdbai commented on src/windows_sys.rs
> +            pub Bvr: [u32; ARM_MAX_BREAKPOINTS],
Fixed in https://github.com/rust-lang/backtrace-rs/pull/685/commits/d468f713270386f9fa5a5bb4404229219141c80e

2024-12-25 09:59 UTC, workingjubilee commented
Thank you. I suppose we will have to think a little on where exactly to put the shim filling, hm.

2025-01-05 02:53 UTC, workingjubilee requested changes
I would prefer to see this code in a separate `.rs` file that is then pulled in via `include!` or `include_str!` as necessary.

2025-01-05 02:53 UTC, workingjubilee commented on src/windows_sys.rs
> +    if #[cfg(target_arch = "arm")] {
This should not need `cfg_if`, though it might require moving the `#[cfg(target_arch = "arm")]` onto conflicting structs maybe?
```suggestion
```

2025-01-05 02:56 UTC, workingjubilee commented
cc @ChrisDenton

2025-01-06 08:51 UTC, bdbai commented on src/windows_sys.rs
> +    if #[cfg(target_arch = "arm")] {
I just put the cfg guard in `windows_sys.rs` for the whole `include!` directive.

2025-01-22 05:07 UTC, ChrisDenton approved these changes
This look right to me, thanks! Sorry for the delay, still catching up from the holidays.

2025-02-13 00:35 UTC, merged